language: java

jdk:
  - openjdk8

branches:
  only:
    - master
    - 3.4
    - 3.5

install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -B

after_success:
  - mvn deploy --settings $HOME/.m2/settings.xml